name: Process Repo Files

on:
  push:
    branches:
      - main

jobs:
  clone-and-process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: 'AMWA-TV/is-04'
          ref: 'v1.3.1'  # Or whatever tag/version you want to process
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci
      
      - name: Process files
        run: node main.js  # Run your script here to process the files

      - name: Upload processed files
        uses: actions/upload-artifact@v2
        with:
          name: processed-files
          path: /path/to/processed/files  # Replace with the path to your processed files
